version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '6001:8000'
    environment:
      NODE_ENV: production
      PORT: 8000
      DB_HOST: host.docker.internal
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    extra_hosts:
      - 'gestionepilates:127.0.0.1'
    stdin_open: true
    tty: true
    restart: always
